version: "3.4"

services:
  db:
    container_name: ereon_web-db
    image: mariadb:10.9.5
    restart: always
    expose:
      - 3306
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    env_file:
      - .env
      - .env.local
    networks:
      - database
  php:
    container_name: ereon_web-php
    build:
      context: .
    ports:
      - "80:80"
    entrypoint: ./entrypoint.sh
    depends_on:
      - db
    networks:
      - database

networks:
  database: