version: "3.4"

services:
  ereon-web:
    container_name: ereon-web
    image: nginx:alpine
    expose:
      - 80
    networks:
      - proxy
      - database
    volumes:
      - ereon:/var/www:rw
      - ereon-uploads:/var/www/public/uploads:rw
      - ./docker/nginx/ereon.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - ereon-php
  ereon-php:
    container_name: ereon-php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    networks:
      - database
      - proxy
    expose:
      - 9000
    volumes:
      - ereon:/var/www/:rw
      - ereon-uploads:/var/www/public/uploads:rw
  ereon-db:
    container_name: ereon-db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
      - .env.local
    expose:
      - 5432
    networks:
      - database
    volumes:
      - ereon-db_data:/var/lib/postgresql/data:rw
  ereon-mercure:
    container_name: ereon-mercure
    image: dunglas/mercure:v0.14
    expose:
      - 3000
    networks:
      - proxy
    environment:
      SERVER_NAME: ':3000'
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins "https://lescanardsmousquetaires.fr"
        anonymous
    env_file:
      - .env
      - .env.local
  
networks:
  database:
    name: database
  proxy:
    name: proxy

volumes:
  ereon:
  ereon-uploads:
  ereon-db_data: