version: "3.4"

services:
  db:
    container_name: ereon_web-db
    image: mariadb:10.9.5
    restart: always
    env_file:
      - .env
    expose:
      - 3306
    networks:
      - database
    volumes:
      - ereon_web-db_data:/var/lib/mysql
  php:
    container_name: ereon_web-php
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    expose:
      - 80
    depends_on:
      - db
    networks:
      - database
      - proxy
networks:
  database:
    name: database
  proxy:
    name: proxy

volumes:
  ereon_web-db_data: