version: "3.4"

services:
  db:
    container_name: ereon_web-db
    image: mariadb:10.9.5
    restart: always
    env_file:
      - .env
    expose:
      - "3306"
    networks:
      - database
    volumes:
      - ereon_web-db_data:/var/lib/mysql
  php:
    container_name: ereon_web-php
    build:
      context: .
    ports:
      - "80:80"
    entrypoint: ./entrypoint.sh
    depends_on:
      - db
    networks:
      - database
  adminer:
    container_name: ereon_web-adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - database

networks:
  database:
    driver: bridge

volumes:
  ereon_web-db_data: