<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230917010453 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE alteration_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE alteration_change_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE asset_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE attribute_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE connection_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE cost_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE currency_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE damage_or_resistance_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE damage_or_resistance_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE dice_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE expense_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE image_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_information_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE map_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE money_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE music_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE music_player_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE number_of_attribute_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE number_of_point_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE number_of_skill_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personage_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE playlist_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE point_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE skill_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE spell_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE token_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "user_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_parameter_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE world_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE alteration (id INT NOT NULL, world_id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9FE087C48925311C ON alteration (world_id)');
        $this->addSql('CREATE TABLE alteration_personage (alteration_id INT NOT NULL, personage_id INT NOT NULL, PRIMARY KEY(alteration_id, personage_id))');
        $this->addSql('CREATE INDEX IDX_42A62F31242F17C7 ON alteration_personage (alteration_id)');
        $this->addSql('CREATE INDEX IDX_42A62F31EA8E3E4A ON alteration_personage (personage_id)');
        $this->addSql('CREATE TABLE alteration_change (id INT NOT NULL, alteration_id INT NOT NULL, attribute_id INT DEFAULT NULL, skill_id INT DEFAULT NULL, value INT DEFAULT NULL, percentage INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4F74B076242F17C7 ON alteration_change (alteration_id)');
        $this->addSql('CREATE INDEX IDX_4F74B076B6E62EFA ON alteration_change (attribute_id)');
        $this->addSql('CREATE INDEX IDX_4F74B0765585C142 ON alteration_change (skill_id)');
        $this->addSql('CREATE TABLE armor (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE asset (id INT NOT NULL, image VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE attribute (id INT NOT NULL, world_id INT NOT NULL, name VARCHAR(255) NOT NULL, acronym VARCHAR(3) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FA7AEFFB8925311C ON attribute (world_id)');
        $this->addSql('CREATE TABLE connection (id INT NOT NULL, world_id INT NOT NULL, user_id INT NOT NULL, current_map_id INT NOT NULL, is_game_master BOOLEAN NOT NULL, last_connection_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_29F773668925311C ON connection (world_id)');
        $this->addSql('CREATE INDEX IDX_29F77366A76ED395 ON connection (user_id)');
        $this->addSql('CREATE INDEX IDX_29F77366540C850A ON connection (current_map_id)');
        $this->addSql('CREATE TABLE cost (id INT NOT NULL, money_id INT NOT NULL, item_information_id INT NOT NULL, value DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_182694FCBF29332C ON cost (money_id)');
        $this->addSql('CREATE INDEX IDX_182694FC3F1D96F5 ON cost (item_information_id)');
        $this->addSql('CREATE TABLE currency (id INT NOT NULL, world_id INT NOT NULL, name VARCHAR(255) NOT NULL, acronym VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6956883F8925311C ON currency (world_id)');
        $this->addSql('CREATE TABLE damage_or_resistance (id INT NOT NULL, type_id INT NOT NULL, weapon_id INT DEFAULT NULL, armor_id INT DEFAULT NULL, spell_id INT DEFAULT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_17DD25DCC54C8C93 ON damage_or_resistance (type_id)');
        $this->addSql('CREATE INDEX IDX_17DD25DC95B82273 ON damage_or_resistance (weapon_id)');
        $this->addSql('CREATE INDEX IDX_17DD25DCF5AA3663 ON damage_or_resistance (armor_id)');
        $this->addSql('CREATE INDEX IDX_17DD25DC479EC90D ON damage_or_resistance (spell_id)');
        $this->addSql('CREATE TABLE damage_or_resistance_type (id INT NOT NULL, world_id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8AC0C8938925311C ON damage_or_resistance_type (world_id)');
        $this->addSql('CREATE TABLE dice (id INT NOT NULL, attribute_id INT DEFAULT NULL, personage_id INT DEFAULT NULL, launcher_id INT NOT NULL, world_id INT NOT NULL, dice_number INT NOT NULL, brut_value INT NOT NULL, final_value INT NOT NULL, computation VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A10EE254B6E62EFA ON dice (attribute_id)');
        $this->addSql('CREATE INDEX IDX_A10EE254EA8E3E4A ON dice (personage_id)');
        $this->addSql('CREATE INDEX IDX_A10EE2542724B909 ON dice (launcher_id)');
        $this->addSql('CREATE INDEX IDX_A10EE2548925311C ON dice (world_id)');
        $this->addSql('CREATE TABLE expense (id INT NOT NULL, point_id INT NOT NULL, spell_id INT NOT NULL, value INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6C028CEA2 ON expense (point_id)');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6479EC90D ON expense (spell_id)');
        $this->addSql('CREATE TABLE image (id INT NOT NULL, image_name VARCHAR(255) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN image.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE item (id INT NOT NULL, item_information_id INT NOT NULL, personage_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1F1B251E3F1D96F5 ON item (item_information_id)');
        $this->addSql('CREATE INDEX IDX_1F1B251EEA8E3E4A ON item (personage_id)');
        $this->addSql('CREATE TABLE item_information (id INT NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, dtype VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE map (id INT NOT NULL, world_id INT NOT NULL, name VARCHAR(255) NOT NULL, width INT NOT NULL, height INT NOT NULL, has_dynamic_light BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_93ADAABB8925311C ON map (world_id)');
        $this->addSql('CREATE TABLE money (id INT NOT NULL, currency_id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, acronym VARCHAR(255) DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B7DF13E438248176 ON money (currency_id)');
        $this->addSql('CREATE TABLE music (id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, link VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE music_player (id INT NOT NULL, world_id INT NOT NULL, current_music_id INT DEFAULT NULL, is_playing BOOLEAN NOT NULL, is_looping BOOLEAN NOT NULL, current_time_play DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DC1B99C8925311C ON music_player (world_id)');
        $this->addSql('CREATE INDEX IDX_DC1B99CA4E3C139 ON music_player (current_music_id)');
        $this->addSql('CREATE TABLE number_of_attribute (id INT NOT NULL, attribute_id INT NOT NULL, personage_id INT NOT NULL, value INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_35580BC4B6E62EFA ON number_of_attribute (attribute_id)');
        $this->addSql('CREATE INDEX IDX_35580BC4EA8E3E4A ON number_of_attribute (personage_id)');
        $this->addSql('CREATE TABLE number_of_point (id INT NOT NULL, point_id INT NOT NULL, personage_id INT NOT NULL, current INT NOT NULL, min INT NOT NULL, max INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_88C25F45C028CEA2 ON number_of_point (point_id)');
        $this->addSql('CREATE INDEX IDX_88C25F45EA8E3E4A ON number_of_point (personage_id)');
        $this->addSql('CREATE TABLE number_of_skill (id INT NOT NULL, skill_id INT NOT NULL, personage_id INT NOT NULL, value INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_615A48165585C142 ON number_of_skill (skill_id)');
        $this->addSql('CREATE INDEX IDX_615A4816EA8E3E4A ON number_of_skill (personage_id)');
        $this->addSql('CREATE TABLE personage (id INT NOT NULL, image_id INT DEFAULT NULL, user_id INT DEFAULT NULL, world_id INT NOT NULL, name VARCHAR(255) NOT NULL, race VARCHAR(255) DEFAULT NULL, alignment VARCHAR(255) DEFAULT NULL, class VARCHAR(255) DEFAULT NULL, inventory TEXT DEFAULT NULL, biography TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E60A6EC53DA5256D ON personage (image_id)');
        $this->addSql('CREATE INDEX IDX_E60A6EC5A76ED395 ON personage (user_id)');
        $this->addSql('CREATE INDEX IDX_E60A6EC58925311C ON personage (world_id)');
        $this->addSql('CREATE TABLE playlist (id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE playlist_music (playlist_id INT NOT NULL, music_id INT NOT NULL, PRIMARY KEY(playlist_id, music_id))');
        $this->addSql('CREATE INDEX IDX_6E4E3B096BBD148 ON playlist_music (playlist_id)');
        $this->addSql('CREATE INDEX IDX_6E4E3B09399BBB13 ON playlist_music (music_id)');
        $this->addSql('CREATE TABLE point (id INT NOT NULL, world_id INT NOT NULL, acronym VARCHAR(3) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B7A5F3248925311C ON point (world_id)');
        $this->addSql('CREATE TABLE skill (id INT NOT NULL, attribute_id INT DEFAULT NULL, world_id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E3DE477B6E62EFA ON skill (attribute_id)');
        $this->addSql('CREATE INDEX IDX_5E3DE4778925311C ON skill (world_id)');
        $this->addSql('CREATE TABLE spell (id INT NOT NULL, world_id INT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, scope INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D03FCD8D8925311C ON spell (world_id)');
        $this->addSql('CREATE TABLE spell_attribute (spell_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY(spell_id, attribute_id))');
        $this->addSql('CREATE INDEX IDX_1ABB6ADC479EC90D ON spell_attribute (spell_id)');
        $this->addSql('CREATE INDEX IDX_1ABB6ADCB6E62EFA ON spell_attribute (attribute_id)');
        $this->addSql('CREATE TABLE spell_personage (spell_id INT NOT NULL, personage_id INT NOT NULL, PRIMARY KEY(spell_id, personage_id))');
        $this->addSql('CREATE INDEX IDX_6CBEBE2479EC90D ON spell_personage (spell_id)');
        $this->addSql('CREATE INDEX IDX_6CBEBE2EA8E3E4A ON spell_personage (personage_id)');
        $this->addSql('CREATE TABLE token (id INT NOT NULL, asset_id INT DEFAULT NULL, map_id INT NOT NULL, width INT NOT NULL, height INT NOT NULL, top_position INT NOT NULL, left_position INT NOT NULL, z_index INT NOT NULL, layer INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5F37A13B5DA1941 ON token (asset_id)');
        $this->addSql('CREATE INDEX IDX_5F37A13B53C55F64 ON token (map_id)');
        $this->addSql('CREATE TABLE token_user (token_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(token_id, user_id))');
        $this->addSql('CREATE INDEX IDX_EF97E32B41DEE7B9 ON token_user (token_id)');
        $this->addSql('CREATE INDEX IDX_EF97E32BA76ED395 ON token_user (user_id)');
        $this->addSql('CREATE TABLE "user" (id INT NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, discord_identifier VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE TABLE user_parameter (id INT NOT NULL, user_id INT NOT NULL, is_dark_theme BOOLEAN NOT NULL, global_volume DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2A771CF4A76ED395 ON user_parameter (user_id)');
        $this->addSql('CREATE TABLE weapon (id INT NOT NULL, scope INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE weapon_attribute (weapon_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY(weapon_id, attribute_id))');
        $this->addSql('CREATE INDEX IDX_18B3815D95B82273 ON weapon_attribute (weapon_id)');
        $this->addSql('CREATE INDEX IDX_18B3815DB6E62EFA ON weapon_attribute (attribute_id)');
        $this->addSql('CREATE TABLE world (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE alteration ADD CONSTRAINT FK_9FE087C48925311C FOREIGN KEY (world_id) REFERENCES world (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alteration_personage ADD CONSTRAINT FK_42A62F31242F17C7 FOREIGN KEY (alteration_id) REFERENCES alteration (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alteration_personage ADD CONSTRAINT FK_42A62F31EA8E3E4A FOREIGN KEY (personage_id) REFERENCES personage (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alteration_change ADD CONSTRAINT FK_4F74B076242F17C7 FOREIGN KEY (alteration_id) REFERENCES alteration (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alteration_change ADD CONSTRAINT FK_4F74B076B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alteration_change ADD CONSTRAINT FK_4F74B0765585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE armor ADD CONSTRAINT FK_BF27FEFCBF396750 FOREIGN KEY (id) REFERENCES item_information (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attribute ADD CONSTRAINT FK_FA7AEFFB8925311C FOREIGN KEY (world_id) REFERENCES world (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE connection ADD CONSTRAINT FK_29F773668925311C FOREIGN KEY (world_id) REFERENCES world (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE connection ADD CONSTRAINT FK_29F77366A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE connection ADD CONSTRAINT FK_29F77366540C850A FOREIGN KEY (current_map_id) REFERENCES map (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cost ADD CONSTRAINT FK_182694FCBF29332C FOREIGN KEY (money_id) REFERENCES money (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cost ADD CONSTRAINT FK_182694FC3F1D96F5 FOREIGN KEY (item_information_id) REFERENCES item_information (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE currency ADD CONSTRAINT FK_6956883F8925311C FOREIGN KEY (world_id) REFERENCES world (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE damage_or_resistance ADD CONSTRAINT FK_17DD25DCC54C8C93 FOREIGN KEY (type_id) REFERENCES damage_or_resistance_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE damage_or_resistance ADD CONSTRAINT FK_17DD25DC95B82273 FOREIGN KEY (weapon_id) REFERENCES weapon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE damage_or_resistance ADD CONSTRAINT FK_17DD25DCF5AA3663 FOREIGN KEY (armor_id) REFERENCES armor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE damage_or_resistance ADD CONSTRAINT FK_17DD25DC479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE damage_or_resistance_type ADD CONSTRAINT FK_8AC0C8938925311C FOREIGN KEY (world_id) REFERENCES world (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dice ADD CONSTRAINT FK_A10EE254B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dice ADD CONSTRAINT FK_A10EE254EA8E3E4A FOREIGN KEY (personage_id) REFERENCES personage (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dice ADD CONSTRAINT FK_A10EE2542724B909 FOREIGN KEY (launcher_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dice ADD CONSTRAINT FK_A10EE2548925311C FOREIGN KEY (world_id) REFERENCES world (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6C028CEA2 FOREIGN KEY (point_id) REFERENCES point (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E3F1D96F5 FOREIGN KEY (item_information_id) REFERENCES item_information (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251EEA8E3E4A FOREIGN KEY (personage_id) REFERENCES personage (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE map ADD CONSTRAINT FK_93ADAABB8925311C FOREIGN KEY (world_id) REFERENCES world (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE money ADD CONSTRAINT FK_B7DF13E438248176 FOREIGN KEY (currency_id) REFERENCES currency (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE music_player ADD CONSTRAINT FK_DC1B99C8925311C FOREIGN KEY (world_id) REFERENCES world (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE music_player ADD CONSTRAINT FK_DC1B99CA4E3C139 FOREIGN KEY (current_music_id) REFERENCES music (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE number_of_attribute ADD CONSTRAINT FK_35580BC4B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE number_of_attribute ADD CONSTRAINT FK_35580BC4EA8E3E4A FOREIGN KEY (personage_id) REFERENCES personage (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE number_of_point ADD CONSTRAINT FK_88C25F45C028CEA2 FOREIGN KEY (point_id) REFERENCES point (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE number_of_point ADD CONSTRAINT FK_88C25F45EA8E3E4A FOREIGN KEY (personage_id) REFERENCES personage (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE number_of_skill ADD CONSTRAINT FK_615A48165585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE number_of_skill ADD CONSTRAINT FK_615A4816EA8E3E4A FOREIGN KEY (personage_id) REFERENCES personage (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personage ADD CONSTRAINT FK_E60A6EC53DA5256D FOREIGN KEY (image_id) REFERENCES image (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personage ADD CONSTRAINT FK_E60A6EC5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personage ADD CONSTRAINT FK_E60A6EC58925311C FOREIGN KEY (world_id) REFERENCES world (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE playlist_music ADD CONSTRAINT FK_6E4E3B096BBD148 FOREIGN KEY (playlist_id) REFERENCES playlist (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE playlist_music ADD CONSTRAINT FK_6E4E3B09399BBB13 FOREIGN KEY (music_id) REFERENCES music (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE point ADD CONSTRAINT FK_B7A5F3248925311C FOREIGN KEY (world_id) REFERENCES world (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE477B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE4778925311C FOREIGN KEY (world_id) REFERENCES world (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE spell ADD CONSTRAINT FK_D03FCD8D8925311C FOREIGN KEY (world_id) REFERENCES world (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE spell_attribute ADD CONSTRAINT FK_1ABB6ADC479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE spell_attribute ADD CONSTRAINT FK_1ABB6ADCB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE spell_personage ADD CONSTRAINT FK_6CBEBE2479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE spell_personage ADD CONSTRAINT FK_6CBEBE2EA8E3E4A FOREIGN KEY (personage_id) REFERENCES personage (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE token ADD CONSTRAINT FK_5F37A13B5DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE token ADD CONSTRAINT FK_5F37A13B53C55F64 FOREIGN KEY (map_id) REFERENCES map (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE token_user ADD CONSTRAINT FK_EF97E32B41DEE7B9 FOREIGN KEY (token_id) REFERENCES token (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE token_user ADD CONSTRAINT FK_EF97E32BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_parameter ADD CONSTRAINT FK_2A771CF4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE weapon ADD CONSTRAINT FK_6933A7E6BF396750 FOREIGN KEY (id) REFERENCES item_information (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE weapon_attribute ADD CONSTRAINT FK_18B3815D95B82273 FOREIGN KEY (weapon_id) REFERENCES weapon (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE weapon_attribute ADD CONSTRAINT FK_18B3815DB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE alteration_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE alteration_change_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE asset_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE attribute_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE connection_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE cost_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE currency_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE damage_or_resistance_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE damage_or_resistance_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE dice_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE expense_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE image_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_information_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE map_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE money_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE music_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE music_player_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE number_of_attribute_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE number_of_point_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE number_of_skill_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personage_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE playlist_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE point_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE skill_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE spell_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE token_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "user_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE user_parameter_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE world_id_seq CASCADE');
        $this->addSql('ALTER TABLE alteration DROP CONSTRAINT FK_9FE087C48925311C');
        $this->addSql('ALTER TABLE alteration_personage DROP CONSTRAINT FK_42A62F31242F17C7');
        $this->addSql('ALTER TABLE alteration_personage DROP CONSTRAINT FK_42A62F31EA8E3E4A');
        $this->addSql('ALTER TABLE alteration_change DROP CONSTRAINT FK_4F74B076242F17C7');
        $this->addSql('ALTER TABLE alteration_change DROP CONSTRAINT FK_4F74B076B6E62EFA');
        $this->addSql('ALTER TABLE alteration_change DROP CONSTRAINT FK_4F74B0765585C142');
        $this->addSql('ALTER TABLE armor DROP CONSTRAINT FK_BF27FEFCBF396750');
        $this->addSql('ALTER TABLE attribute DROP CONSTRAINT FK_FA7AEFFB8925311C');
        $this->addSql('ALTER TABLE connection DROP CONSTRAINT FK_29F773668925311C');
        $this->addSql('ALTER TABLE connection DROP CONSTRAINT FK_29F77366A76ED395');
        $this->addSql('ALTER TABLE connection DROP CONSTRAINT FK_29F77366540C850A');
        $this->addSql('ALTER TABLE cost DROP CONSTRAINT FK_182694FCBF29332C');
        $this->addSql('ALTER TABLE cost DROP CONSTRAINT FK_182694FC3F1D96F5');
        $this->addSql('ALTER TABLE currency DROP CONSTRAINT FK_6956883F8925311C');
        $this->addSql('ALTER TABLE damage_or_resistance DROP CONSTRAINT FK_17DD25DCC54C8C93');
        $this->addSql('ALTER TABLE damage_or_resistance DROP CONSTRAINT FK_17DD25DC95B82273');
        $this->addSql('ALTER TABLE damage_or_resistance DROP CONSTRAINT FK_17DD25DCF5AA3663');
        $this->addSql('ALTER TABLE damage_or_resistance DROP CONSTRAINT FK_17DD25DC479EC90D');
        $this->addSql('ALTER TABLE damage_or_resistance_type DROP CONSTRAINT FK_8AC0C8938925311C');
        $this->addSql('ALTER TABLE dice DROP CONSTRAINT FK_A10EE254B6E62EFA');
        $this->addSql('ALTER TABLE dice DROP CONSTRAINT FK_A10EE254EA8E3E4A');
        $this->addSql('ALTER TABLE dice DROP CONSTRAINT FK_A10EE2542724B909');
        $this->addSql('ALTER TABLE dice DROP CONSTRAINT FK_A10EE2548925311C');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6C028CEA2');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6479EC90D');
        $this->addSql('ALTER TABLE item DROP CONSTRAINT FK_1F1B251E3F1D96F5');
        $this->addSql('ALTER TABLE item DROP CONSTRAINT FK_1F1B251EEA8E3E4A');
        $this->addSql('ALTER TABLE map DROP CONSTRAINT FK_93ADAABB8925311C');
        $this->addSql('ALTER TABLE money DROP CONSTRAINT FK_B7DF13E438248176');
        $this->addSql('ALTER TABLE music_player DROP CONSTRAINT FK_DC1B99C8925311C');
        $this->addSql('ALTER TABLE music_player DROP CONSTRAINT FK_DC1B99CA4E3C139');
        $this->addSql('ALTER TABLE number_of_attribute DROP CONSTRAINT FK_35580BC4B6E62EFA');
        $this->addSql('ALTER TABLE number_of_attribute DROP CONSTRAINT FK_35580BC4EA8E3E4A');
        $this->addSql('ALTER TABLE number_of_point DROP CONSTRAINT FK_88C25F45C028CEA2');
        $this->addSql('ALTER TABLE number_of_point DROP CONSTRAINT FK_88C25F45EA8E3E4A');
        $this->addSql('ALTER TABLE number_of_skill DROP CONSTRAINT FK_615A48165585C142');
        $this->addSql('ALTER TABLE number_of_skill DROP CONSTRAINT FK_615A4816EA8E3E4A');
        $this->addSql('ALTER TABLE personage DROP CONSTRAINT FK_E60A6EC53DA5256D');
        $this->addSql('ALTER TABLE personage DROP CONSTRAINT FK_E60A6EC5A76ED395');
        $this->addSql('ALTER TABLE personage DROP CONSTRAINT FK_E60A6EC58925311C');
        $this->addSql('ALTER TABLE playlist_music DROP CONSTRAINT FK_6E4E3B096BBD148');
        $this->addSql('ALTER TABLE playlist_music DROP CONSTRAINT FK_6E4E3B09399BBB13');
        $this->addSql('ALTER TABLE point DROP CONSTRAINT FK_B7A5F3248925311C');
        $this->addSql('ALTER TABLE skill DROP CONSTRAINT FK_5E3DE477B6E62EFA');
        $this->addSql('ALTER TABLE skill DROP CONSTRAINT FK_5E3DE4778925311C');
        $this->addSql('ALTER TABLE spell DROP CONSTRAINT FK_D03FCD8D8925311C');
        $this->addSql('ALTER TABLE spell_attribute DROP CONSTRAINT FK_1ABB6ADC479EC90D');
        $this->addSql('ALTER TABLE spell_attribute DROP CONSTRAINT FK_1ABB6ADCB6E62EFA');
        $this->addSql('ALTER TABLE spell_personage DROP CONSTRAINT FK_6CBEBE2479EC90D');
        $this->addSql('ALTER TABLE spell_personage DROP CONSTRAINT FK_6CBEBE2EA8E3E4A');
        $this->addSql('ALTER TABLE token DROP CONSTRAINT FK_5F37A13B5DA1941');
        $this->addSql('ALTER TABLE token DROP CONSTRAINT FK_5F37A13B53C55F64');
        $this->addSql('ALTER TABLE token_user DROP CONSTRAINT FK_EF97E32B41DEE7B9');
        $this->addSql('ALTER TABLE token_user DROP CONSTRAINT FK_EF97E32BA76ED395');
        $this->addSql('ALTER TABLE user_parameter DROP CONSTRAINT FK_2A771CF4A76ED395');
        $this->addSql('ALTER TABLE weapon DROP CONSTRAINT FK_6933A7E6BF396750');
        $this->addSql('ALTER TABLE weapon_attribute DROP CONSTRAINT FK_18B3815D95B82273');
        $this->addSql('ALTER TABLE weapon_attribute DROP CONSTRAINT FK_18B3815DB6E62EFA');
        $this->addSql('DROP TABLE alteration');
        $this->addSql('DROP TABLE alteration_personage');
        $this->addSql('DROP TABLE alteration_change');
        $this->addSql('DROP TABLE armor');
        $this->addSql('DROP TABLE asset');
        $this->addSql('DROP TABLE attribute');
        $this->addSql('DROP TABLE connection');
        $this->addSql('DROP TABLE cost');
        $this->addSql('DROP TABLE currency');
        $this->addSql('DROP TABLE damage_or_resistance');
        $this->addSql('DROP TABLE damage_or_resistance_type');
        $this->addSql('DROP TABLE dice');
        $this->addSql('DROP TABLE expense');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE item');
        $this->addSql('DROP TABLE item_information');
        $this->addSql('DROP TABLE map');
        $this->addSql('DROP TABLE money');
        $this->addSql('DROP TABLE music');
        $this->addSql('DROP TABLE music_player');
        $this->addSql('DROP TABLE number_of_attribute');
        $this->addSql('DROP TABLE number_of_point');
        $this->addSql('DROP TABLE number_of_skill');
        $this->addSql('DROP TABLE personage');
        $this->addSql('DROP TABLE playlist');
        $this->addSql('DROP TABLE playlist_music');
        $this->addSql('DROP TABLE point');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE spell');
        $this->addSql('DROP TABLE spell_attribute');
        $this->addSql('DROP TABLE spell_personage');
        $this->addSql('DROP TABLE token');
        $this->addSql('DROP TABLE token_user');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_parameter');
        $this->addSql('DROP TABLE weapon');
        $this->addSql('DROP TABLE weapon_attribute');
        $this->addSql('DROP TABLE world');
    }
}
