name: Push and Deploy

on:
  push:
    branches:
      - main

default:
  run:
    timeout-minutes: 20

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /home/matiou/Ereon-web
          git pull origin main
          docker-compose down
          docker volume rm ereon-web_ereon
          docker-compose up --build -d